invoice/urls.py
from django.urls import path

from invoice import views


urlpatterns = [
    # 一覧画面
    path('',  views.InvoiceFilterView.as_view(template_name = "invoice/invoice_filter.html"), name='index'),
    # 詳細画面
    path('detail/<int:pk>/', views.InvoiceDetailView.as_view(template_name = "invoice/invoice_detail.html"), name='detail'),
    # 登録画面
    path('create/', views.InvoiceCreateView.as_view(template_name = "invoice/invoice_form.html"), name='create'),
    # 更新画面
    path('update/<int:pk>/', views.InvoiceCreateView.as_view(template_name = "invoice/invoice_form.html"), name='update'),
    # 削除画面
    path('delete/<int:pk>/', views.InvoiceDeleteView.as_view(template_name = "invoice/invoice_confirm_delete.html"), name='delete'),
    
    path("index/",views.HomeTemplateView.as_view(template_name = "invoice/index.html"), name="blogs"),

]

invoiceproject/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('invoice.urls')),
]

invoice/models.py
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.urls import reverse


class Item(models.Model):
    name = models.CharField(
        verbose_name='名前',
        max_length=100,
    )

    unit_price = models.IntegerField(
        verbose_name='単価',
        validators=[validators.MinValueValidator(0)],
    )

    order = models.IntegerField(
        verbose_name='並び順',
        validators=[validators.MinValueValidator(0)],
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'メニュー'
        verbose_name_plural = 'メニュー'


class Invoice(models.Model):
    customer = models.CharField(
        verbose_name='テーブルNoを入力してください',
        max_length=100,
    )

    sub_total = models.IntegerField(
        verbose_name='小計',
    )

    tax = models.IntegerField(
        verbose_name='消費税',
    )

    total_amount = models.IntegerField(
        verbose_name='合計金額',
    )

    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='作成者',
    )

    created_at = models.DateTimeField(
        verbose_name='登録日',
        auto_now_add=True
    )

    def __str__(self):
        return self.customer

    class Meta:
        verbose_name = '注文'
        verbose_name_plural = '注文'

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])


class InvoiceDetail(models.Model):
    invoice = models.ForeignKey(
        Invoice,
        on_delete=models.CASCADE)

    item = models.ForeignKey(
        Item,
        verbose_name='商品',
        on_delete=models.CASCADE,
    )

    unit_price = models.IntegerField(
        verbose_name='単価',
        validators=[validators.MinValueValidator(0)],
    )

    quantity = models.IntegerField(
        verbose_name='数量',
        validators=[validators.MinValueValidator(0)],
    )

    amount = models.IntegerField(
        verbose_name='金額',
    )

invoice/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.forms.widgets import Select

from .models import Item, Invoice, InvoiceDetail


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = ('customer',)


class InvoiceDetailForm(forms.ModelForm):
    class Meta:
        model = InvoiceDetail
        fields = ('item', 'quantity',)

    def __init__(self, *args, **kwargs):
        super(InvoiceDetailForm, self).__init__(*args, **kwargs)

        self.fields['item'].choices = lambda: [('', '-- 商品 --')] + [
            (item.id, '%s %s円' % (item.name.ljust(10, '　'), item.unit_price)) for item in
            Item.objects.order_by('order')]

        choices_number = [('', '-- 個数 --')] + [(str(i), str(i)) for i in range(1, 10)]
        self.fields['quantity'].widget = Select(choices=choices_number)


InvoiceDetailFormSet = inlineformset_factory(
    parent_model=Invoice,
    model=InvoiceDetail,
    form=InvoiceDetailForm,
    extra=1,
    min_num=1,
    validate_min=True,
)

invoice/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView
from pure_pagination.mixins import PaginationMixin

from django.views.generic import TemplateView

from .filters import InvoiceFilter
from .forms import InvoiceForm, InvoiceDetailFormSet
from .models import Invoice


class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class InvoiceMixin(object):
    def form_valid(self, form, formset):

        # formset.saveでインスタンスを取得できるように、既存データに変更が無くても更新対象となるようにする
        for detail_form in formset.forms:
            if detail_form.cleaned_data:
                detail_form.has_changed = lambda: True

        # インスタンスの取得
        invoice = form.save(commit=False)
        formset.instance = invoice
        details = formset.save(commit=False)

        sub_total = 0

        # 明細に単価と合計を設定
        for detail in details:
            detail.unit_price = detail.item.unit_price
            detail.amount = detail.unit_price * detail.quantity
            sub_total += detail.amount

        # 見出しに小計、消費税、合計、担当者を設定
        tax = round(sub_total * 0.08)
        total_amount = sub_total + tax

        invoice.sub_total = sub_total
        invoice.tax = tax
        invoice.total_amount = total_amount
        invoice.created_by = self.request.user

        # DB更新
        with transaction.atomic():
            invoice.save()
            formset.instance = invoice
            formset.save()

        # 処理後は詳細ページを表示
        return redirect(invoice.get_absolute_url())


class InvoiceFilterView(LoginRequiredMixin, PaginationMixin, FilterView):
    model = Invoice
    filterset_class = InvoiceFilter
    # デフォルトの並び順を新しい順とする
    queryset = Invoice.objects.all().order_by('-created_at')

    # pure_pagination用設定
    paginate_by = 10
    object = Invoice

    # 検索条件をセッションに保存する
    def get(self, request, **kwargs):
        if request.GET:
            request.session['query'] = request.GET
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]

        return super().get(request, **kwargs)


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = Invoice


class InvoiceCreateView(LoginRequiredMixin, InvoiceMixin, FormsetMixin, CreateView):
    template_name = 'invoice/invoice_form.html'
    model = Invoice
    form_class = InvoiceForm
    formset_class = InvoiceDetailFormSet


class InvoiceUpdateView(LoginRequiredMixin, InvoiceMixin, FormsetMixin, UpdateView):
    is_update_view = True
    template_name = 'invoice/invoice_form.html'
    model = Invoice
    form_class = InvoiceForm
    formset_class = InvoiceDetailFormSet


class InvoiceDeleteView(LoginRequiredMixin, DeleteView):
    model = Invoice
    success_url = reverse_lazy('index')
    
class HomeTemplateView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blogs'] = "ご注文が確定しました"
        return context
    


invoice/templates/invoice/_base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>注文アプリ</title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    <link href="{% static 'invoice/css/invoice.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        {% if request.user.is_authenticated %}
            {{ request.user.get_full_name }}
        {% endif %}</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false"
            aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">管理画面</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:logout' %}">ログアウト</a>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>
{% block content %}
{% endblock %}

{% bootstrap_javascript jquery='full' %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script src="{% static 'invoice/js/invoice.js' %}"></script>

{% block bottom_script %}
{% endblock bottom_script %}

</body>

</html>

invoice/templates/invoice/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% if page == page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endif %}
        {% else %}
            <li class="page-item">
                <span class="page-link">…</span>
            </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item">
            <span class="page-link">&raquo;</span>
        </li>
    {% endif %}
</ul>

invoice/templates/invoice/index.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ja">

    <head>
        <!-- Required meta tags always come first -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>注文アプリ</title>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        <link href="{% static 'invoice/css/invoice.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid">
            
            <div class="clearfix">
                <div class="col no-gutters">
                    <img class="img-fluid" src="/static/invoice/img/thanks.png" alt="">
                </div>
                <h2>{{ blogs }}</h2>
                <h3>ご提供までしばらくお待ちください</h3>
                <div class="col no-gutters">
                    <img class="img-fluid" src="/static/invoice/img/fav.png" alt="">
                </div>
            </div>
        </div>
    </body>







    </html>

invoice/templates/invoice/invoice_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8 offset-sm-2">
                <h2 class="text-center">データ削除</h2>
                <p>このデータを削除します。よろしいですか？</p>

                <form action="" method="post" id="myform">
                    {% csrf_token %}
                    <div class="clearfix">
                        <div class="float-right">
                            <a class="btn btn-outline-secondary command" href="{% url 'detail' invoice.pk %}">戻る</a>
                            <a class="btn btn-outline-secondary command save" href="#">削除</a>
                        </div>
                    </div>
                    {% include "./invoice_detail_content.html" %}
                    <div class="clearfix">
                        <div class="float-right">
                            <a class="btn btn-outline-secondary command" href="{% url 'detail' invoice.pk %}">戻る</a>
                            <a class="btn btn-outline-secondary command save" href="#">削除</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

invoice/templates/invoice/invoice_detail.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>注文アプリ</title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    <link href="{% static 'invoice/css/invoice.css' %}" rel="stylesheet">
</head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    <h2 class="text-center">ご注文内容の確認</h2>
                    <div class="clearfix">
                        <div class="float-right mt-1 mb-3">
                            <!-- <a class="btn btn-outline-secondary command" href="{% url 'delete' invoice.pk %}">注文確定</a> -->
                            <!-- <a class="btn btn-outline-secondary command" href="{% url 'update' invoice.pk %}">やり直す</a> -->
                            <!-- <a class="btn btn-outline-secondary command" href="{% url 'index' %}">戻る</a> -->
                        </div>
                    </div>
                    <div>
                        {% include "./invoice_detail_content.html" %}
                    </div>
                    <div class="float-right mt-1 mb-1">
                        <!-- <a class="btn btn-outline-secondary command" href="{% url 'delete' invoice.pk %}">注文確定</a> -->
                        <a class="btn btn-outline-secondary command" href="{% url 'blogs'  %}">注文確定</a>
                        <a class="btn btn-outline-secondary command" href="{% url 'update' invoice.pk %}">やり直す</a>
                        <!-- <a class="btn btn-outline-secondary command" href="{% url 'index' %}">戻る</a> -->
                    </div>
                </div>
            </div>
        </div>
    
    </body>
    
</html>

invoice/templates/invoice/invoice_detail_content.html
{% load humanize %}
<div class="row">
    <div class="col-3">
        <p>テーブルNo.</p>
    </div>
    <div class="col-9">
        <p>{{ invoice.customer }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>登録日</p>
    </div>
    <div class="col-9">
        <p>{{ invoice.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <!-- <p>担当者</p> -->
    </div>
    <div class="col-9">
        <p>{{ invoice.created_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <table class="table table-sm table-striped table-bordered ">
            <thead class="thead-dark">
            <tr>
                <th></th>
                <th>商品名</th>
                <th>単価</th>
                <th>個数</th>
                <th>合計</th>
            </tr>
            </thead>
            <tbody>
            {% for detail in invoice.invoicedetail_set.all %}
                <tr>
                    <td class="rownum"></td>
                    <td>{{ detail.item }}</td>
                    <td class="number">{{ detail.unit_price|intcomma:False }}</td>
                    <td class="number">{{ detail.quantity|intcomma:False }}</td>
                    <td class="number">{{ detail.amount|intcomma:False }} 円</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td colspan="3"></td>
                <th>小計</th>
                <td class="number">{{ invoice.sub_total|intcomma:False }} 円</td>
            </tr>
            <tr>
                <td colspan="3"></td>
                <th>消費税</th>
                <td class="number">{{ invoice.tax|intcomma:False }} 円</td>
            </tr>
            <tr>
                <td colspan="3"></td>
                <th>合計</th>
                <td class="number">{{ invoice.total_amount|intcomma:False }} 円</td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>

invoice/templates/invoice/invoice_filter.html
{% extends "./_base.html" %}
{% load bootstrap4 %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8 offset-sm-2">

                <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">検索条件</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <form id="filter" method="get">
                                <div class="modal-body">
                                    {% bootstrap_form filter.form %}
                                </div>
                            </form>
                            <div class="modal-footer">
                                <a class="btn btn-outline-secondary" data-dismiss="modal">戻る</a>
                                <button type="submit" class="btn btn-outline-secondary" form="filter">検索</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-1">
                    <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
                    <div class="float-right">
                        <a class="btn btn-outline-secondary command" href="{% url 'create' %}">新規</a>
                        <a class="btn btn-outline-secondary command" data-toggle="modal" data-target="#myModal"
                        href="#">検索</a>
                    </div>
                </div>
                <div class="mt-1">
                    {% include "./_pagination.html" %}
                </div>

                <ul class="list-group">
                    {% for invoice in invoice_list %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-3">
                                    <p>顧客名</p>
                                </div>
                                <div class="col-9">
                                    <p>{{ invoice.customer }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                    <p>担当者</p>
                                </div>
                                <div class="col-9">
                                    <p>{{ invoice.created_by.get_full_name }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                    <p>登録日</p>
                                </div>
                                <div class="col-9">
                                    <p>{{ invoice.created_at|date:"Y/m/d G:i:s" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="float-right">
                                        <a class="btn btn-outline-secondary"
                                        href="{% url 'detail' invoice.pk %}">詳細表示</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">
                            対象のデータがありません
                        </li>
                    {% endfor %}
                </ul>
                <div class="mt-1 float-right">
                    <a class="btn btn-outline-secondary command" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-outline-secondary command" data-toggle="modal" data-target="#myModal"
                    href="#">検索</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

invoice/templates/invoice/invoice_form.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ja">

    <head>
        <!-- Required meta tags always come first -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>注文アプリ</title>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        <link href="{% static 'invoice/css/invoice.css' %}" rel="stylesheet">
    </head>
    <body>
        {{ form.certifications.errors }}
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-8 offset-sm-2">
                    
                    
                    
                    <div class="clearfix">
                        <div class="col no-gutters">
                            <img class="img-fluid" src="/static/invoice/img/cafe.png" alt="">
                        </div>
                        <div class="float-right mt-3 mb-3">
                            <!-- {% if object %}
                                <a class="btn btn-outline-secondary command" href="{% url 'detail' invoice.pk %}">戻る</a>
                            {% else %}
                                <a class="btn btn-outline-secondary command" href="{% url 'index' %}">戻る</a>
                            {% endif %} -->
                            <a class="btn btn-outline-secondary command save" href="#">注文登録</a>
                        </div>
                    </div>
                    <div>
                        {% bootstrap_formset_errors formset %}
                    </div>
                    <form method="post" class="form" id="myform">
                        {% csrf_token %}
                        {{ formset.management_form }}
                        {% bootstrap_field form.customer show_label=False %}
                        <div>
                            <table class="table table-striped">
                                <tbody class="invoicedetail">
                                {% for form in formset %}
                                    <tr>
                                        <td class="align-middle rownum"></td>
                                        <td>
                                            {% bootstrap_field form.id show_label=False %}
                                            {% bootstrap_field form.item show_label=False %}
                                            {% bootstrap_field form.quantity show_label=False %}
                                            {% bootstrap_field form.DELETE show_label=False field_class="float-right" %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <a href="#" class="btn btn-outline-secondary add-invoicedetail col-12">行を追加</a>
                    </form>
                    <div class="float-right mt-3 mb-3">
                        <!-- {% if object %}
                            <a class="btn btn-outline-secondary command" href="{% url 'detail' invoice.pk %}">戻る</a>
                        {% else %}
                            <a class="btn btn-outline-secondary command" href="{% url 'index' %}">戻る</a>
                        {% endif %} -->
                        <a class="btn btn-outline-secondary command save" href="#">注文登録</a>
                    </div>
                </div>
            </div>
        </div>


        {% block bottom_script %}
            <script type="text/html" id="invoicedetail-template">
                <tr id="invoicedetail-__prefix__">
                    <td class="align-middle rownum"></td>
                    <td>
                        {% bootstrap_field formset.empty_form.item show_label=False %}
                        {% bootstrap_field formset.empty_form.quantity show_label=False %}
                        {% bootstrap_field formset.empty_form.DELETE show_label=False field_class="float-right" %}
                    </td>
                </tr>
            </script>
            {% bootstrap_javascript jquery='full' %}
            <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
            <script src="{% static 'invoice/js/invoice.js' %}"></script>
            <script>
                $(function () {
                    $('.add-invoicedetail').click(function (e) {
                        e.preventDefault();
                        var count = parseInt($('#id_invoicedetail_set-TOTAL_FORMS').attr('value'), 10);
                        var tmplMarkup = $('#invoicedetail-template').html();
                        var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count)
                        console.log(compiledTmpl);
                        $('tbody.invoicedetail').append(compiledTmpl);
                        $('#id_invoicedetail_set-TOTAL_FORMS').attr('value', count + 1);
                    });
                });
            </script>
        {% endblock bottom_script %}
    </body>
    
</html>